// Generated by CoffeeScript 1.3.3
var FreeAgent, crypto, proxyUrl, qs, request, _;

request = require('request');

crypto = require('crypto');

qs = require('querystring');

_ = require('underscore');

proxyUrl = process.env.HTTPS_PROXY || process.env.https_proxy;

FreeAgent = (function() {

  function FreeAgent(access_token, sandboxMode) {
    this.access_token = access_token;
    if (sandboxMode) {
      this.baseUri = 'https://api.sandbox.freeagent.com/v2/';
    } else {
      this.baseUri = 'https://api.freeagent.com/v2/';
    }
  }

  FreeAgent.prototype._prepareHeaders = function(access_token, options) {
    if (!options) {
      options = {};
    }
    return _.extend(options, {
      proxy: proxyUrl,
      headers: {
        'Accept': 'application/json',
        'User-Agent': 'node-freeagent2',
        'Authorization': "Bearer " + access_token
      }
    });
  };

  FreeAgent.prototype._getRequest = function(url, options, callback) {
    var requestUri;
    if (!callback) {
      throw new Error("No callback defined!");
    }
    requestUri = this.baseUri + url;
    if (options) {
      requestUri += '?' + qs.stringify(options);
    }
    return request.get(this._prepareHeaders(this.access_token, {
      uri: requestUri,
      json: true
    }), function(error, response, body) {
      if (!error) {
        if (response.statusCode < 400) {
          return callback(null, body);
        } else {
          return callback(new Error("" + response.statusCode + " : " + body));
        }
      } else {
        return callback(error);
      }
    });
  };

  FreeAgent.prototype.getCompany = function(optionsOrCallback, callback) {
    var options;
    if (typeof optionsOrCallback === 'function') {
      callback = optionsOrCallback;
    } else {
      options = optionsOrCallback;
    }
    return this._getRequest('company', null, function(error, data) {
      if (!error && data && data.company) {
        return callback(null, data.company);
      } else {
        return callback(error);
      }
    });
  };

  FreeAgent.prototype.getProjects = function(optionsOrCallback, callback) {
    return this._getRequest('projects', null, callback);
  };

  FreeAgent.prototype.getProjectWithId = function(projectUri, optionsOrCallback, callback) {
    return this._getRequest('projects/' + projectUri, null, callback);
  };

  FreeAgent.prototype.getTasksForProject = function(projectUri, optionsOrCallback, callback) {
    return this._getRequest('tasks/' + projectUri, null, callback);
  };

  FreeAgent.prototype.getUsers = function(optionsOrCallback, callback) {
    return this._getRequest('users', null, callback);
  };

  FreeAgent.prototype.getTimeslips = function(optionsOrCallback, callback) {
    return this._getRequest('timeslips', null, callback);
  };

  FreeAgent.prototype.getInvoices = function(optionsOrCallback, callback) {
    return this._getRequest('invoices', null, callback);
  };

  FreeAgent.prototype.getInvoicesForProject = function(projectUri, optionsOrCallback, callback) {
    return this._getRequest('invoices', {
      project: projectUri
    }, callback);
  };

  return FreeAgent;

})();

module.exports = FreeAgent;
